# My personal repositories I want cloned and installed.
- https://github.com/evanthegrayt/list-and-grep
- https://github.com/evanthegrayt/list-and-count
- https://github.com/evanthegrayt/spoonerise
- https://github.com/evanthegrayt/bulk-delete-slack-files
- https://github.com/evanthegrayt/rock-paper-scissors
- https://github.com/evanthegrayt/exed
- https://github.com/evanthegrayt/mkex
- https://github.com/evanthegrayt/bash-lib
- https://github.com/evanthegrayt/grayt-FSyH-theme

